// types.ts - All TypeScript interfaces and types
// Every interface and type used throughout the application lives here.
// Keeping all types in one place ensures consistency across the codebase.

// ---- CONFIGURATION TYPES ----

// main application configuration loaded from .env file
export interface Config {
  mode: "PAPER" | "LIVE"; // trading mode
  // api credentials (alpaca for both data and trading)
  alpacaApiKey: string;
  alpacaSecretKey: string;
  alpacaBaseUrl: string;
  // discord bot
  discordBotToken: string;
  discordGuildId: string;
  discordChannelTrades: string;
  discordChannelSystem: string;
  discordChannelErrors: string;
  // trading settings
  symbols: string[]; // array of stock symbols to trade
  maxTradesPerDay: number; // maximum trades per day per symbol
  strategyCutoffTime: string; // time to stop entering new trades (EST)
  // position sizing
  positionSizeMode: "FIXED" | "RISK_BASED";
  fixedPositionSize: number; // dollar amount for FIXED mode
  accountRiskPercent: number; // percentage for RISK_BASED mode
  maxPositionValue: number; // maximum position size in dollars
  minPositionValue: number; // minimum position size in dollars
  // risk management
  riskRewardRatio: number; // target profit vs risk ratio (e.g., 2.0 = 2:1)
  stopLossBufferPercent: number; // buffer added to stop loss
  // ATR-based stops
  useAtrStops: boolean; // use ATR for stops instead of opening range
  atrPeriod: number; // ATR calculation period (e.g., 14)
  atrStopMultiplier: number; // ATR multiplier for stops (e.g., 1.5)
  // trailing stops
  useTrailingStops: boolean; // enable trailing stops
  trailingStopActivation: number; // R-multiple to activate trailing (e.g., 1.0 = 1R)
  trailingStopAtrMultiple: number; // ATR distance for trailing stop
  // partial exits
  usePartialExits: boolean; // enable partial profit taking
  partialExitAtRMultiple: number; // R-multiple to take partial profit (e.g., 1.0)
  partialExitPercent: number; // percentage to exit (e.g., 50 = 50%)
  // adaptive position sizing (size based on signal quality)
  useAdaptivePositionSizing: boolean; // enable signal-based sizing
  weakSignalSizePercent: number; // position size for weak signals (e.g., 50 = 50%)
  // opening range filters
  openingRangeMinSize: number; // minimum range as % of price
  openingRangeMaxSize: number; // maximum range as % of price
  // fair value gap (FVG) rules
  fvgBodyPercent: number; // required body size as % of candle range
  fvgMinRangePercent: number; // minimum candle range as % of price
  fvgOverlapTolerance: number; // allowed gap overlap as %
  fvgClosePositionPercent: number; // where close must be in candle range
  requireVolumeConfirmation: boolean; // require volume spike
  volumeMultiplier: number; // volume multiplier for confirmation
  // logging
  logLevel: "normal" | "debug";
  saveCandleData: boolean; // save candles to JSON files
  // earnings filter
  skipEarningsDays: boolean; // skip trading on earnings days
  // opening range strength filter
  openingRangeMinStrength: number; // minimum OR strength score (0-10)
  // volume safety threshold
  minAbsoluteVolumePerMinute: number; // minimum volume per minute (prevents low liquidity)
  // stale breakout timeout
  maxFvgWindowMinutes: number; // max time to complete FVG after breakout
  // pre-market gap filter
  maxPremarketGapPercent: number; // maximum pre-market gap allowed
}

// ---- MARKET DATA TYPES ----

// single candlestick with OHLC data
export interface Candle {
  symbol: string; // stock symbol (e.g., "SPY")
  timestamp: Date; // candle timestamp in EST
  open: number; // opening price
  high: number; // highest price
  low: number; // lowest price
  close: number; // closing price
  volume: number; // trading volume
  vwap?: number; // volume-weighted average price (for quality analysis)
  tradeCount?: number; // number of trades (detects institutional vs retail)
}

// opening range calculated from first 5-minute candle
export interface OpeningRange {
  high: number; // high of opening range
  low: number; // low of opening range
  size: number; // range size as % of price
  sizeInDollars: number; // range size in dollars
  timestamp: Date; // when range was established
}

// ---- STRATEGY TYPES ----

// trading signal generated by strategy
export interface Signal {
  symbol: string; // what to trade
  direction: "LONG" | "SHORT"; // buy or sell
  timestamp: Date; // when signal was generated
  currentPrice: number; // price at signal generation
  reason: string; // why this signal was generated
}

// fair value gap pattern detection result
export interface FVGPattern {
  detected: boolean; // was pattern found
  direction: "BULLISH" | "BEARISH" | null; // pattern direction
  candle1: Candle; // first candle (breakout)
  candle2: Candle; // second candle (momentum)
  candle3: Candle; // third candle (gap)
  details: string; // human-readable explanation
}

// breakout detection result
export interface Breakout {
  detected: boolean; // did price break range
  direction: "ABOVE" | "BELOW" | null; // which way
  candle: Candle; // candle that broke range
  openingRange: OpeningRange; // the range that was broken
}

// ---- POSITION & ORDER TYPES ----

// active trading position
export interface Position {
  symbol: string; // what we're holding
  side: "LONG" | "SHORT"; // direction
  entryPrice: number; // price we entered at
  quantity: number; // number of shares
  entryTime: Date; // when we entered
  stopLoss: number; // stop loss price
  takeProfit: number; // take profit price
  orderIds: {
    entry: string; // entry order ID
    stopLoss: string; // stop loss order ID
    takeProfit: string; // take profit order ID
  };
  // trailing stop tracking
  initialStopLoss: number; // original stop loss
  highestPrice?: number; // highest price since entry (for LONG)
  lowestPrice?: number; // lowest price since entry (for SHORT)
  trailingStopActive: boolean; // is trailing stop enabled
  // partial exit tracking
  originalQuantity: number; // quantity at entry
  partialExitExecuted: boolean; // has partial exit occurred
}

// order to be placed with broker
export interface Order {
  symbol: string; // what to trade
  side: "BUY" | "SELL"; // buy or sell
  quantity: number; // number of shares
  type: "MARKET" | "LIMIT" | "STOP"; // order type
  price?: number; // limit/stop price (if applicable)
  timeInForce: "DAY" | "GTC"; // order duration
}

// result of position sizing calculation
export interface PositionSize {
  symbol: string; // what we're sizing for
  quantity: number; // number of shares to trade
  dollarValue: number; // total dollar value of position
  entryPrice: number; // price we'll enter at
  stopPrice: number; // stop loss price
  targetPrice: number; // take profit price
  riskPerShare: number; // risk per share in dollars
  totalRisk: number; // total dollar risk
  potentialProfit: number; // potential dollar profit
  riskRewardRatio: number; // ratio of profit to risk
}

// ---- TRADE TRACKING TYPES ----

// completed trade with full details
export interface Trade {
  id: string; // unique trade ID
  symbol: string; // what was traded
  side: "LONG" | "SHORT"; // direction
  entryTime: Date; // when we entered
  entryPrice: number; // entry price
  quantity: number; // number of shares
  exitTime: Date; // when we exited
  exitPrice: number; // exit price
  exitReason: "TAKE_PROFIT" | "STOP_LOSS" | "MANUAL" | "END_OF_DAY"; // why we exited
  pnl: number; // profit/loss in dollars
  pnlPercent: number; // profit/loss as percentage
  fees: number; // trading fees
  holdingTime: number; // how long we held (in seconds)
}

// statistics for tracking performance
export interface TradingStats {
  totalTrades: number; // total number of trades
  wins: number; // number of winning trades
  losses: number; // number of losing trades
  winRate: number; // win rate as percentage
  totalPnL: number; // total profit/loss
  bestTrade: number; // best single trade P&L
  worstTrade: number; // worst single trade P&L
  averageWin: number; // average winning trade
  averageLoss: number; // average losing trade
  currentStreak: {
    type: "WIN" | "LOSS"; // current streak type
    count: number; // how many in a row
  };
  longestWinStreak: number; // longest winning streak
  longestLossStreak: number; // longest losing streak
}

// ---- STATE MANAGEMENT TYPES ----

// daily state for a symbol (persisted to JSON)
export interface DailyState {
  date: string; // trading date (YYYY-MM-DD)
  symbol: string; // stock symbol
  openingRange: OpeningRange | null; // opening range if captured
  openingRangeCandle?: Candle; // full opening range candle for volume/ATR
  tradeExecutedToday: boolean; // have we traded yet today
  tradeCount: number; // number of trades executed today
  sessionStatus:
    | "WAITING"
    | "CAPTURING_RANGE"
    | "MONITORING"
    | "POSITION_OPEN"
    | "DONE"; // current state
  lastUpdated: Date; // last state update time
}

// current position state (persisted to JSON)
export interface CurrentPositionState {
  symbol: string; // what we're holding
  side: "LONG" | "SHORT"; // direction
  entryPrice: number; // entry price
  quantity: number; // number of shares
  entryTime: Date; // entry timestamp
  stopLoss: number; // stop loss price
  takeProfit: number; // take profit price
  orderIds: {
    entry: string; // entry order ID
    stopLoss: string; // stop loss order ID
    takeProfit: string; // take profit order ID
  };
  // trailing stop fields
  initialStopLoss: number; // original stop loss
  highestPrice?: number; // highest price since entry (for LONG)
  lowestPrice?: number; // lowest price since entry (for SHORT)
  trailingStopActive: boolean; // is trailing stop enabled
  // partial exit fields
  originalQuantity: number; // quantity at entry
  partialExitExecuted: boolean; // has partial exit occurred
}

// trade history file structure (persisted to JSON)
export interface TradeHistory {
  date: string; // trading date
  trades: Trade[]; // all trades for this date
}

// all-time statistics (persisted to JSON)
export interface AllTimeStats {
  allTimeStats: TradingStats; // overall statistics
  symbolStats: { [symbol: string]: TradingStats }; // per-symbol stats
  lastUpdated: Date; // last update time
}

// ---- BROKER INTERFACE TYPES ----

// broker account information
export interface AccountInfo {
  equity: number; // total account value
  cash: number; // available cash
  buyingPower: number; // buying power
  dayTradeCount: number; // pattern day trades in last 5 days
  positions: Position[]; // open positions
}

// result of an order execution
export interface OrderResult {
  success: boolean; // was order successful
  orderId: string; // order ID from broker
  filledPrice?: number; // price order was filled at
  filledQuantity?: number; // quantity that was filled
  error?: string; // error message if failed
}

// ---- MARKET HOURS TYPES ----

// market hours and status
export interface MarketHours {
  isOpen: boolean; // is market currently open
  nextOpen: Date; // next market open time
  nextClose: Date; // next market close time
  hoursUntilOpen: number; // hours until next open
  hoursUntilClose: number; // hours until next close
}

// ---- REJECTION TRACKING TYPES ----

// single rejection event
export interface Rejection {
  timestamp: Date; // when rejection occurred
  symbol: string; // symbol that was rejected
  stage: RejectionStage; // at what stage rejection happened
  reason: string; // human-readable reason
  details?: any; // additional context (optional)
}

// rejection stages
export type RejectionStage =
  | "PRE_MARKET_GAP" // gap too large
  | "OPENING_RANGE_SIZE" // size outside limits
  | "OPENING_RANGE_STRENGTH" // strength score too low
  | "BREAKOUT_VOLUME" // breakout volume too low
  | "FVG_PATTERN" // FVG requirements not met
  | "TIME_WINDOW" // outside allowed hours
  | "MARKET_REGIME" // against market trend
  | "SIGNAL_QUALITY" // signal quality too weak
  | "EARNINGS_EVENT"; // earnings day

// daily rejection log
export interface RejectionLog {
  date: string; // trading date
  rejections: Rejection[]; // all rejections for this date
}

// ---- STRATEGY CONFIG TYPES (loaded from strategies.json) ----

// schedule settings - when the strategy runs
export interface StrategySchedule {
  sessionSetupEnd: string; // HH:MM EST, when the setup phase ends
  tradingCutoff: string; // HH:MM EST, no new entries after this time
  marketClose: string; // HH:MM EST, market close time
  pollingIntervalMs: number; // ms between candle polls during monitoring
  maxStaleDataMinutes: number; // reject candles older than this many minutes
}

// ---- ORB STRATEGY PARAMETER TYPES ----
// these define the params for the Opening Range Breakout strategy
// in strategies.json, these go inside the strategy's "params" object

// opening range filter settings
export interface ORFilterConfig {
  minSize: number; // minimum range as % of price
  maxSize: number; // maximum range as % of price
  minStrength: number; // minimum strength score 0-10
  maxPremarketGap: number; // max pre-market gap as % from prev close
  skipEarningsDays: boolean; // skip trading on earnings days
}

// breakout detection settings
export interface BreakoutConfig {
  volumeMultiplier: number; // required volume vs OR avg (e.g. 1.2 = 20% above)
  minAbsoluteVolume: number; // minimum volume per candle
  maxFvgWindowMinutes: number; // max time after breakout to find FVG
}

// FVG (fair value gap) pattern settings
export interface FVGConfig {
  bodyPercent: number; // required body size as % of candle range
  minRangePercent: number; // minimum candle range as % of price
  overlapTolerance: number; // allowed gap overlap as %
  closePositionPercent: number; // where close must be in candle range
  requireVolumeConfirmation: boolean; // require volume spike on FVG
  volumeMultiplier: number; // volume multiplier for FVG confirmation
}

// position sizing settings
export interface PositionSizingConfig {
  mode: "FIXED" | "RISK_BASED"; // sizing mode
  fixedSize: number; // dollar amount for FIXED mode
  accountRiskPercent: number; // % of account for RISK_BASED mode
  maxValue: number; // max position dollar value
  minValue: number; // min position dollar value
  useAdaptive: boolean; // reduce size for weak signals
  weakSignalSizePercent: number; // size % for weak signals (e.g. 50 = half)
}

// risk management settings
export interface RiskManagementConfig {
  riskRewardRatio: number; // target R:R (e.g. 2.0 = 2:1)
  stopLossBufferPercent: number; // buffer added to stop loss
  useAtrStops: boolean; // use ATR for stop calc instead of OR
  atrPeriod: number; // ATR lookback period
  atrStopMultiplier: number; // ATR multiplier for stop distance
  useTrailingStops: boolean; // enable trailing stops
  trailingStopActivation: number; // R-multiple to activate trailing
  trailingStopAtrMultiple: number; // ATR multiple for trailing distance
  usePartialExits: boolean; // enable partial profit taking
  partialExitAtRMultiple: number; // R-multiple to trigger partial exit
  partialExitPercent: number; // % of position to exit
}

// discord notification routing - env var names for channel IDs
export interface NotificationConfig {
  trades: string; // env var name for trades channel
  system: string; // env var name for system channel
  errors: string; // env var name for errors channel
}

// full strategy configuration - one entry in strategies.json
// generic fields live here, strategy-specific settings go in the params object
export interface StrategyConfig {
  id: string; // unique strategy identifier
  type: string; // strategy type key (e.g. "opening-range-breakout")
  enabled: boolean; // whether this strategy is active
  symbols: string[]; // symbols this strategy trades
  maxTradesPerDay: number; // max trades per symbol per day
  holdOvernight: boolean; // if true, positions survive across sessions
  schedule: StrategySchedule; // timing config
  notifications: NotificationConfig; // discord channel routing
  params: Record<string, any>; // strategy-specific config
}

// root structure of strategies.json file
export interface StrategiesFile {
  strategies: StrategyConfig[];
}

// ---- STRATEGY RESULT TYPES (returned by IStrategy methods) ----

// result from evaluating opening range candle
export interface OpeningRangeResult {
  accepted: boolean; // true if range qualifies for trading
  openingRange: OpeningRange | null; // the calculated range (null if rejected)
  rejectReason: string; // why it was rejected (empty if accepted)
  strength: number; // strength score 0-10
}

// result from processing a monitoring candle
export interface CandleResult {
  signal: Signal | null; // trading signal if generated
  fvgPattern: FVGPattern | null; // FVG pattern if detected
  done: boolean; // true if strategy is done with this symbol today
  rejectReason: string; // why no signal (empty if signal generated)
}

// what the strategy wants to do on a candle (returned by onCandle)
export interface StrategyAction {
  type: "NONE" | "ENTRY" | "DONE"; // nothing, open a trade, or stop for day
  positionSize: PositionSize | null; // the trade to execute (for ENTRY)
  signal: Signal | null; // signal details for notifications (for ENTRY)
  reason: string; // why done/rejected (for DONE), or signal reason (for ENTRY)
}

// what the strategy wants done with an open position
export interface PositionUpdate {
  doPartialExit: boolean; // execute a partial exit this candle
  partialExitPrice: number; // price for partial exit
  partialExitPercent: number; // % of position to exit
  activateTrailing: boolean; // activate trailing stop
  newStopLoss: number | null; // updated stop loss (null = no change)
  closePosition: boolean; // close the entire position
  closePrice: number; // price to close at
  closeReason: string; // reason for closing (STOP_LOSS, TAKE_PROFIT, etc.)
}
